version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./youtube_slicer.db
      - MINIO_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=youtube-videos
      - MINIO_SECURE=false
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - minio
      - redis
    volumes:
      - ./:/app
      - /home/cat/github/slice-youtube/youtube_cookies.txt:/app/youtube_cookies.txt
    working_dir: /app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./youtube_slicer.db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=youtube-videos
      - MINIO_SECURE=false
      - REDIS_URL=redis://redis:6379
      - COOKIES_FILE=/app/youtube_cookies.txt
      - YOUTUBE_COOKIES_FILE=/app/youtube_cookies.txt
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  minio_data:
  redis_data: